apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rp7gf8bj1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rp7gf8bj1-go 
  name: rp7gf8bj1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rp7gf8bj1-go 
